# Generated by Django 5.2.7 on 2025-10-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_grantapplication_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Grant Application', 'verbose_name_plural': 'Grant Applications'},
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='additional_info',
            field=models.TextField(blank=True, help_text="Anything else you'd like us to know?", verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='budget_breakdown',
            field=models.TextField(default='', help_text='How will the funds be used? Provide detailed breakdown.', verbose_name='Budget Breakdown'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='challenges',
            field=models.TextField(blank=True, help_text='What challenges do you anticipate and how will you address them?', verbose_name='Potential Challenges'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='expected_impact',
            field=models.TextField(default='', help_text='How will you measure success?', verbose_name='Expected Impact'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='experience',
            field=models.TextField(default='', help_text="Describe your organization's or your relevant experience", verbose_name='Relevant Experience'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='implementation_plan',
            field=models.TextField(default='', help_text='How will you execute this project?', verbose_name='Implementation Plan'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='organization_name',
            field=models.CharField(default='', max_length=300, verbose_name='Organization/Project Name'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='organization_type',
            field=models.CharField(choices=[('nonprofit', 'Non-Profit Organization'), ('community', 'Community Group'), ('educational', 'Educational Institution'), ('research', 'Research Organization'), ('social', 'Social Enterprise'), ('individual', 'Individual')], default='nonprofit', max_length=20, verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='other_funding',
            field=models.TextField(blank=True, help_text="List any other grants or funding you've received or applied for", verbose_name='Other Funding Sources'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='project_category',
            field=models.CharField(choices=[('education', 'Education & Learning'), ('health', 'Health & Wellness'), ('environment', 'Environmental'), ('technology', 'Technology & Innovation'), ('community', 'Community Development'), ('arts', 'Arts & Culture'), ('youth', 'Youth Development'), ('elderly', 'Elderly Care'), ('poverty', 'Poverty Alleviation'), ('other', 'Other')], default='community', max_length=20, verbose_name='Project Category'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='project_description',
            field=models.TextField(default='', help_text='Describe your project in detail (minimum 200 words)', verbose_name='Detailed Project Description'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='project_duration',
            field=models.CharField(default='', help_text='e.g., 6 months, 1 year', max_length=100, verbose_name='Project Duration'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='project_goals',
            field=models.TextField(default='', help_text='What do you hope to achieve?', verbose_name='Project Goals & Objectives'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='project_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Proposed Start Date'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='project_title',
            field=models.CharField(default='', max_length=300, verbose_name='Project Title'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='sustainability',
            field=models.TextField(blank=True, help_text='How will the project continue after the grant period?', verbose_name='Sustainability Plan'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='target_beneficiaries',
            field=models.TextField(default='', help_text='Who will benefit from this project?', verbose_name='Target Beneficiaries'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax ID/EIN (if applicable)'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='team_members',
            field=models.TextField(blank=True, help_text='List key people involved and their roles', verbose_name='Key Team Members'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website (if any)'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='years_established',
            field=models.IntegerField(blank=True, null=True, verbose_name='Years Established'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='address',
            field=models.TextField(verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='amount_requested',
            field=models.IntegerField(choices=[(1000, '$1,000'), (2500, '$2,500'), (5000, '$5,000'), (7500, '$7,500'), (10000, '$10,000'), (15000, '$15,000'), (20000, '$20,000'), (25000, '$25,000')], default=1000, verbose_name='Grant Amount Requested'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
    ]
