# Generated by Django 5.2.7 on 2025-10-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_alter_grantapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Approved'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='Approval/Rejection Notes'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='approved_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Approved Amount'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='amount_requested',
            field=models.IntegerField(choices=[(10000, '$10,000'), (15000, '$15,000'), (20000, '$20,000'), (25000, '$25,000'), (30000, '$30,000')], default=10000, verbose_name='Grant Amount Requested'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='organization_type',
            field=models.CharField(choices=[('individual', 'Individual/Personal'), ('family', 'Family'), ('single_parent', 'Single Parent'), ('senior_citizen', 'Senior Citizen'), ('student', 'Student'), ('nonprofit', 'Non-Profit Organization'), ('community', 'Community Group')], default='nonprofit', max_length=20, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='project_category',
            field=models.CharField(choices=[('essential_needs', 'Essential Needs (Food, Utilities, etc.)'), ('healthcare', 'Healthcare & Medical'), ('education', 'Education & Training'), ('housing', 'Housing & Rent Assistance'), ('emergency', 'Emergency Financial Aid'), ('debt_relief', 'Debt Relief'), ('disability', 'Disability Support'), ('senior_care', 'Senior Care'), ('childcare', 'Childcare Support'), ('other', 'Other')], default='community', max_length=20, verbose_name='Project Category'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='pending', max_length=20),
        ),
    ]
