# Generated by Django 5.2.7 on 2025-10-04 00:49

import django.core.validators
import django.db.models.deletion
import grants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_grantapplication_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('max_file_size', models.IntegerField(default=10485760)),
                ('allowed_extensions', models.CharField(default='pdf,doc,docx,jpg,jpeg,png', max_length=200)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='current_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('eligibility', 'Eligibility Screening'), ('details', 'Detailed Application'), ('documents', 'Document Upload'), ('review', 'Under Review'), ('interview', 'Interview/Clarification'), ('decision', 'Final Decision'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='documents_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='documents_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='interview_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='interview_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='interview_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('status_changed', 'Status Changed'), ('document_uploaded', 'Document Uploaded'), ('document_verified', 'Document Verified'), ('funds_disbursed', 'Funds Disbursed'), ('report_submitted', 'Report Submitted'), ('user_login', 'User Login'), ('admin_action', 'Admin Action')], max_length=30)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period', models.CharField(max_length=50)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_breakdown', models.JSONField(default=dict)),
                ('receipts_uploaded', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='grants.grantapplication')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disbursement_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('digital_wallet', 'Digital Wallet'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('disbursed_date', models.DateTimeField()),
                ('bank_details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='grants.grantapplication')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrantAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_applications', models.IntegerField(default=0)),
                ('approved_applications', models.IntegerField(default=0)),
                ('rejected_applications', models.IntegerField(default=0)),
                ('pending_applications', models.IntegerField(default=0)),
                ('total_amount_requested', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_processing_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('geographic_distribution', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='GrantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=grants.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grants.grantapplication')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.documenttype')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('general', 'General'), ('clarification', 'Clarification Request'), ('document', 'Document Related'), ('interview', 'Interview Related'), ('update', 'Status Update')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='grants.grantapplication')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period', models.CharField(max_length=50)),
                ('activities_completed', models.TextField()),
                ('challenges_faced', models.TextField(blank=True)),
                ('funds_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_steps', models.TextField()),
                ('attachments', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='grants.grantapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('impact_description', models.TextField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('photos', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grants.grantapplication')),
            ],
        ),
    ]
