# Generated by Django 5.2.7 on 2025-10-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_documenttype_grantapplication_current_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_deadline_hours', models.IntegerField(default=24, help_text='Hours for approval decision')),
                ('processing_time_weeks_min', models.IntegerField(default=2, help_text='Minimum processing time in weeks')),
                ('processing_time_weeks_max', models.IntegerField(default=4, help_text='Maximum processing time in weeks')),
                ('review_frequency', models.CharField(default='Monthly', help_text='How often applications are reviewed', max_length=50)),
                ('welcome_message', models.TextField(default='Welcome to the David Johnson Foundation Grant Application. Please complete all sections carefully. Our review process typically takes 2-4 weeks. Applications are reviewed monthly by our grant committee.', help_text='Message shown to applicants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grant Settings',
                'verbose_name_plural': 'Grant Settings',
            },
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='additional_info',
            field=models.TextField(blank=True, help_text="Any additional information you'd like to share (optional)", verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='amount_requested',
            field=models.IntegerField(default=10000, help_text='Enter amount in dollars', verbose_name='Grant Amount Requested'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='budget_breakdown',
            field=models.TextField(default='', help_text='Provide a detailed breakdown:\n• Personnel: $X,XXX\n• Equipment: $X,XXX\n• Materials: $X,XXX\n• Other: $X,XXX', verbose_name='Budget Breakdown'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='challenges',
            field=models.TextField(blank=True, help_text='What challenges do you anticipate and how will you address them? (optional)', verbose_name='Potential Challenges'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='experience',
            field=models.TextField(default='', help_text="Describe your organization's relevant experience and qualifications for this project", verbose_name='Relevant Experience'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='implementation_plan',
            field=models.TextField(default='', help_text='Describe your step-by-step plan to implement this project. Include timeline and milestones.', verbose_name='Implementation Plan'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Organization/Project Name'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('nonprofit', 'Non-Profit Organization'), ('community', 'Community Group'), ('religious', 'Religious Organization'), ('educational', 'Educational Institution'), ('healthcare', 'Healthcare Organization'), ('other', 'Other Organization')], default='nonprofit', max_length=20, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='other_funding',
            field=models.TextField(blank=True, help_text='List any other grants, donations, or funding sources (current or pending)', verbose_name='Other Funding Sources'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='project_duration',
            field=models.CharField(default='', help_text='e.g., 6 months, 1 year, 18 months', max_length=100, verbose_name='Project Duration'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='project_start_date',
            field=models.DateField(blank=True, help_text='mm/dd/yyyy', null=True, verbose_name='Proposed Start Date'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='sustainability',
            field=models.TextField(blank=True, help_text='How will the project continue or have lasting impact after the grant period? (optional)', verbose_name='Sustainability Plan'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='tax_id',
            field=models.CharField(blank=True, help_text='For tax-exempt organizations', max_length=50, verbose_name='Tax ID/EIN (if applicable)'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='team_members',
            field=models.TextField(blank=True, help_text='List key team members and their roles/qualifications (optional)', verbose_name='Key Team Members'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='website',
            field=models.URLField(blank=True, help_text='https://www.yourorganization.org', verbose_name='Website (if any)'),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='years_established',
            field=models.IntegerField(blank=True, help_text='e.g., 5', null=True, verbose_name='Years Established'),
        ),
    ]
