# Generated by Django 5.2.7 on 2025-10-05 23:11

import django.db.models.deletion
import grants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_alter_grantapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='photos',
        ),
        migrations.CreateModel(
            name='SuccessStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=grants.models.success_story_image_path)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Main image for this testimonial')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('success_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='grants.successstory')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
